[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "FFI utilities"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "ffi_utils"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.22.0"

[dependencies]
clippy = { version = "=0.0.99", optional = true }
log = "~0.3.6"
rustc-serialize = "~0.3.22"
unwrap = "~1.1.0"

[dev-dependencies]
rand = "~0.3.14"
