[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Authenticator"
documentation = "https://docs.rs/safe_authenticator"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_authenticator"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.9.1"
build = "build.rs"
edition = "2018"

[dependencies]
bincode = "~1.1.4"
config_file_handler = "~0.11.0"
ffi_utils = "~0.12.0"
futures = "~0.1.17"
log = "~0.4.1"
lru-cache = "~0.1.1"
maidsafe_utilities = "~0.18.0"
rand = "~0.3.18"
new_rand = { package = "rand", version = "0.6" }
# routing = "~0.37.0"
# routing = { git = "https://github.com/lionel1704/routing", branch = "patch" }
routing = { package = "mock_routing", path = "../mock_routing" }
rust_sodium = "~0.10.2"
safe_core = { path = "../safe_core", version = "~0.32.1" }
# safe-nd = { git = "https://github.com/maidsafe/safe-nd" }
safe-nd = { path = "../../safe-nd" }
serde = "~1.0.27"
serde_derive = "~1.0.27"
# threshold_crypto = "0.3.1"
threshold_crypto = { git = "https://github.com/nbaksalyar/threshold_crypto.git", branch = "pks-copy" }
tiny-keccak = "~1.4.0"
tokio = "=0.1.8"
tokio-core = "~0.1.17"
unwrap = "~1.2.0"
jni = { version = "~0.12.0", optional = true }

[dev-dependencies.safe_core]
path = "../safe_core"
version = "~0.32.1"
features = ["testing"]

[build-dependencies]
ffi_utils = "~0.12.0"
jni = "~0.12.0"
# routing = "~0.37.0"
routing = { package = "mock_routing", path = "../mock_routing" }
rust_sodium = "~0.10.2"
safe_bindgen = { version = "~0.13.0", optional = true }
unwrap = "~1.2.0"

[features]
mock-network = ["testing", "safe_core/mock-network"]
testing = ["safe_core/testing"]
bindings = ["safe_bindgen"]

[lib]
crate_type = ["staticlib", "rlib", "cdylib"]
