env:
  global:
    - Features=use-mock-routing
    - RUST_BACKTRACE=1
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
branches:
  only:
    - master
    - dev
script:
  - travis_wait 40 . travis_build.sh
  - curl -sSLO https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/run_clippy.sh
  - . run_clippy.sh
