# Travis CI file.
#
# Performs the following:
#
# 1. Runs the binary compatibility test, and generates a new reference binary if pushing to a branch.
# 2. Checks if working tree is dirty after building (i.e. Cargo.lock should be updated).
#
# Both of these functions should eventually be moved to Github Actions and this file deprecated.

env:
  global:
    # Run all cargo commands with --verbose.
    - CARGO_TERM_VERBOSE=true
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
language: rust
rust:
  - stable
stages:
  - build-binary
jobs:
  include:
    # Build tests for binary compatibility (only when pushing)
    - stage: build-binary
      script: scripts/build-binary
      if: type = push
      os: linux
sudo: false
cache:
  # Double the default timeout.
  timeout: 360
  cargo: true
  directories:
    - "${HOME}/.cache/master"
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
after_script:
  - if [[ $TRAVIS_EVENT_TYPE = pull_request && -n $(git diff --shortstat 2> /dev/null | tail -n1) ]]; then
      echo "Working tree is dirty after building.  Probably Cargo.lock should be updated.";
      git status;
      travis_terminate 1;
    fi
before_cache:
  - cargo prune
