env:
  global:
    - Features=use-mock-routing
    - RUST_BACKTRACE=1
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
branches:
  only:
    - master
    - dev
script:
    - cd $TRAVIS_BUILD_DIR
    - if [ "${TRAVIS_RUST_VERSION}" = stable ]; then (set -x; cargo rustc --verbose -- --test -Zno-trans && cargo test --release --features use-mock-routing --verbose); fi
    - if [ "${TRAVIS_RUST_VERSION}" = nightly -a "${TRAVIS_OS_NAME}" = linux ]; then (set -x; cargo rustc --features clippy --verbose -- --test -Zno-trans && cargo rustc --features "clippy use-mock-routing" --verbose -- --test -Zno-trans); fi
