env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C opt-level=2 -C codegen-units=8"
    - PATH=$PATH:$HOME/.cargo/bin
    - S3_BUCKET=safe-client-libs-jenkins
    - S3_ARTIFACTS_PATH=travis-artifacts
language: rust
rust:
  - 1.29.1
install:
  - pip install --user awscli
stages:
  - build
  - tests
  - deploy
jobs:
  include:
    - stage: build
      name: "build real"
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
      script: make build
      before_cache:
        - make package-build-artifacts
        - mkdir -p ~/.artifacts-linux-real
        - cp artifacts/** ~/.artifacts-linux-real
        - rm -rf target
      env:
        - SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - SCL_BUILD_MOCK=false
        - SCL_BUILD_OS=$TRAVIS_OS_NAME
      os: linux
    - stage: build
      name: "build mock"
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
      script: make build-mock
      before_cache:
        - make package-build-artifacts
        - mkdir -p ~/.artifacts-linux-mock
        - cp artifacts/** ~/.artifacts-linux-mock
        - rm -rf target
      env:
        - SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - SCL_BUILD_MOCK=true
        - SCL_BUILD_OS=$TRAVIS_OS_NAME
      os: linux
    - stage: build
      name: "build real"
      script: set -x; scripts/build-real
      before_cache:
        - make package-build-artifacts
        - mkdir -p ~/.artifacts-osx-real
        - cp artifacts/** ~/.artifacts-osx-real
        - rm -rf target
        - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
        - bash cargo_install.sh cargo-prune;
        - cargo prune
      env:
        - SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - SCL_BUILD_MOCK=false
        - SCL_BUILD_OS=$TRAVIS_OS_NAME
      os: osx
    - stage: build
      name: "build mock"
      script: set -x; scripts/build-mock
      before_cache:
        - make package-build-artifacts
        - mkdir -p ~/.artifacts-osx-mock
        - cp artifacts/** ~/.artifacts-osx-mock
        - rm -rf target
        - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
        - bash cargo_install.sh cargo-prune;
        - cargo prune
      env:
        - SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - SCL_BUILD_MOCK=true
        - SCL_BUILD_OS=$TRAVIS_OS_NAME
      os: osx

    - stage: tests
      name: "mock tests"
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
        - rm -rf artifacts && mkdir artifacts
        - tar -C artifacts -xvf ~/.artifacts-linux-mock/$TRAVIS_BUILD_NUMBER-scl-mock-linux-x86_64.tar.gz
      script: make test-artifacts-mock
      os: linux
    - stage: tests
      name: "integration tests"
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
        - rm -rf artifacts && mkdir artifacts
        - tar -C artifacts -xvf ~/.artifacts-linux-mock/$TRAVIS_BUILD_NUMBER-scl-mock-linux-x86_64.tar.gz
      script: make test-artifacts-integration
      os: linux
    - stage: tests
      name: "binary compatibility tests"
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
        - rm -rf artifacts && mkdir artifacts
        - tar -C artifacts -xvf ~/.artifacts-linux-mock/$TRAVIS_BUILD_NUMBER-scl-mock-linux-x86_64.tar.gz
        # If there is no previous binary compatibility test suite available, use the current one.
        # This situation should only ever occur on the first time the build runs since expecting the file to exist.
        - set -e;
          if [[ ! -f "~/.artifacts-bct/binary-compatibility-tests" ]]; then
            find artifacts -maxdepth 1 -name 'safe_authenticator-*' ! -name '*.d' -exec cp '{}' ~/.artifacts-bct/binary-compatibility-tests \; ;
          fi;
      script: make test-artifacts-binary
      after_success: find artifacts -maxdepth 1 -name 'safe_authenticator-*' ! -name '*.d' -exec cp '{}' ~/.artifacts-bct/binary-compatibility-tests \; ;
      os: linux
    - stage: tests
      name: "mock/integration tests"
      script: set -x; scripts/test-mock && scripts/test-integration
      os: osx
    # Temporarily disable clippy
    # - stage: tests
    #   script: set -x; scripts/clippy-all
    #   if: type = pull_request
    #   os: linux

    - stage: deploy
      name: "package artifacts and deploy"
      install: pip install --user awscli
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
        - make retrieve-all-build-artifacts
      script: make package-deploy-artifacts
      deploy:
        provider: s3
        access_key_id: AKIAJI7QGOMYIJIFOYNA
        secret_access_key:
          secure: VuScHhXnvdlR2tSw/9PM8jKMraSRpblCx3NqN+SkVDWwhF585KPdtoE4dHevaBh9Qwh76YgG8l7FJ1Q5ac+zOzfSgdhjUjGtvnBhjrwH6Yi/tDqi4KdK6unz0ZFbHuLRRbcrgC1aSU0QK2HJHcM66SOvKMd6Lol0jZKqSETtb2CKco3mSQgTPRhlulhfGYTLlefxf5FFUiyEy//JCKORJV4/s1cb6LcjA6QrmUb8TkDl3kxywRRFDH/0MWwd/X1v1Y4sDH8Ucfy8hT0S1AgcPZCrd/CHwl2G7l4n5Nl1BrDc/dlFuw9IdE56O+JOQb1DgOg5ZG/9zpOgX6vpE2jwgkueGe9A1z+4DsWhopNPTyi4y9uPb9R2DBp1q99/ePlW0lCx/bAsKzDn2lO2MiZY2mIQ04z+FjzK9Tia8jikSiZoPZeJbS7il/SV0wRlMaX2jcWIuzY/knNtf2ZjTTeIwIv5TktZvTdJcyrUuOa8pRvWbCOx/XnZsaD/PtrGYgrYJBdbHpfsToUB6T5A7QL7wV+7F+8VuGgFJlGH6ybXRZV1DJIUFqMUheX1cfHmh5kuGMgTbVj8HKfvprVlSa9HNJi42pzF2qKYkJEqLgZj2cMfqN+EYrXLbaxY6yZseNvb5OKOA+iN2JHxQEDtHCXlOBb2UN4nu2obycKAGOTMNdE=
        bucket: safe-client-libs
        local-dir: deploy
        acl: public_read
        region: eu-west-2
        skip_cleanup: true
        on:
          branch: master
          tags: false
      after_deploy:
        - rm -rf deploy
        - rm -rf artifacts
      if: type = push
      env: SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
      os: linux
sudo: false
cache:
  # Double the default timeout.
  timeout: 360
  cargo: true
  directories:
    - "${HOME}/.cache/master"
    - "${HOME}/.artifacts-linux-real"
    - "${HOME}/.artifacts-linux-mock"
    - "${HOME}/.artifacts-osx-real"
    - "${HOME}/.artifacts-osx-mock"
    - "${HOME}/.artifacts-bct"
before_script:
  - scripts/version-check
after_script:
  - if [[ $TRAVIS_EVENT_TYPE = pull_request && -n $(git diff --shortstat 2> /dev/null | tail -n1) ]]; then
      echo "Working tree is dirty after building.  Probably Cargo.lock should be updated.";
      git status;
      travis_terminate 1;
    fi
