env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C opt-level=2 -C codegen-units=8"
    - PATH=$PATH:$HOME/.cargo/bin
    - S3_BUCKET=safe-client-libs-jenkins
    - S3_ARTIFACTS_PATH=travis-artifacts
language: rust
rust:
  - 1.29.1
install:
  - pip install --user awscli
stages:
  - build
  - tests
  - deploy
jobs:
  include:
    - stage: build
      name: "build real"
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
      script: make build
      after_script: make strip-artifacts
      before_cache:
        # We don't need target cached when we use a container.
        - rm -rf target
      before_deploy: make package-build-artifacts
      deploy:
        provider: s3
        access_key_id: AKIAIYOCYHBTBC6XUFYQ
        secret_access_key:
          secure: NQnKN7Tk4EG3psaOJLdrZexHtaEeFdECH5u5buvILKkZgyphLafu6P5zqX5XyIZqoL30WjR1aF71HQhZvQwgoCxT6cr/8rk9dXFu6ZLXJ8dCqEN5I/cc9dWplJpgSOj1bELOJBEDZBWMnwOC6PapE0+SRjnaLbp8IswqQTz78m3Evrcrze2p90TQzvui23D2yo9mxncQc8+dXh1o9J+3u3ODA+6y32CR/gX5hkiO3fKBXjOh0bLBy0nGW1xU7zNTlc//7lv+rbDQHXTp4W+lImZdA7TyGbBHNOA95zGW1BrxIZO2d7A72AxqUBYfkYKN/Ml6TsTMeW+IHpbeT4T39JFngq2fDzBPd+zcUWZLJLTDcUoiDlAZ0DSiTet4OIqRgJS2Mm3iktsbLov76CHgd4zDL3gJG4KeIbWrvNw2nrPANk6EY1PEpBgU+oe1u1zlesYlj10koaTg+AooikHWZc/JgAIAdjY4tfEonAUJ/dirbzCmCkXWuCnX/7ZVVsE7RpSLCQ9HE/uVVC2r71O7dTGaFsm14q3tsmceqkw/ha5ZyLsZhan9GitLST2bNerZn3QFMJI3sviLdECm1GSbGY3shVSIeeKy1GhTUINXXQfyldmHhgfrgJpo7T1U0Q9iUdtE9mX4MaLhJkHlnPsKqH+StKnB3AHmxDXXWqCPcHw=
        bucket: $S3_BUCKET
        local_dir: artifacts
        upload_dir: $S3_ARTIFACTS_PATH
        acl: public_read
        region: eu-west-2
        skip_cleanup: true
        on:
          all_branches: true
      after_deploy: rm -rf artifacts
      env:
        - SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - SCL_BUILD_MOCK=false
        - SCL_BUILD_OS=$TRAVIS_OS_NAME
      os: linux
    - stage: build
      name: "build mock"
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
      script: make build-mock
      after_script: make strip-artifacts
      before_cache:
        # We don't need target cached when we use a container.
        - rm -rf target
      before_deploy: make package-build-artifacts
      deploy:
        provider: s3
        access_key_id: AKIAIYOCYHBTBC6XUFYQ
        secret_access_key:
          secure: NQnKN7Tk4EG3psaOJLdrZexHtaEeFdECH5u5buvILKkZgyphLafu6P5zqX5XyIZqoL30WjR1aF71HQhZvQwgoCxT6cr/8rk9dXFu6ZLXJ8dCqEN5I/cc9dWplJpgSOj1bELOJBEDZBWMnwOC6PapE0+SRjnaLbp8IswqQTz78m3Evrcrze2p90TQzvui23D2yo9mxncQc8+dXh1o9J+3u3ODA+6y32CR/gX5hkiO3fKBXjOh0bLBy0nGW1xU7zNTlc//7lv+rbDQHXTp4W+lImZdA7TyGbBHNOA95zGW1BrxIZO2d7A72AxqUBYfkYKN/Ml6TsTMeW+IHpbeT4T39JFngq2fDzBPd+zcUWZLJLTDcUoiDlAZ0DSiTet4OIqRgJS2Mm3iktsbLov76CHgd4zDL3gJG4KeIbWrvNw2nrPANk6EY1PEpBgU+oe1u1zlesYlj10koaTg+AooikHWZc/JgAIAdjY4tfEonAUJ/dirbzCmCkXWuCnX/7ZVVsE7RpSLCQ9HE/uVVC2r71O7dTGaFsm14q3tsmceqkw/ha5ZyLsZhan9GitLST2bNerZn3QFMJI3sviLdECm1GSbGY3shVSIeeKy1GhTUINXXQfyldmHhgfrgJpo7T1U0Q9iUdtE9mX4MaLhJkHlnPsKqH+StKnB3AHmxDXXWqCPcHw=
        bucket: $S3_BUCKET
        local_dir: artifacts
        upload_dir: $S3_ARTIFACTS_PATH
        acl: public_read
        region: eu-west-2
        skip_cleanup: true
        on:
          all_branches: true
      after_deploy: rm -rf artifacts
      env:
        - SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - SCL_BUILD_MOCK=true
        - SCL_BUILD_OS=$TRAVIS_OS_NAME
      os: linux
    - stage: build
      name: "build real"
      script: set -x; scripts/build-real
      after_script: make strip-artifacts
      before_cache:
        - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
        - bash cargo_install.sh cargo-prune;
        - cargo prune
      before_deploy: make package-build-artifacts
      deploy:
        provider: s3
        access_key_id: AKIAIYOCYHBTBC6XUFYQ
        secret_access_key:
          secure: NQnKN7Tk4EG3psaOJLdrZexHtaEeFdECH5u5buvILKkZgyphLafu6P5zqX5XyIZqoL30WjR1aF71HQhZvQwgoCxT6cr/8rk9dXFu6ZLXJ8dCqEN5I/cc9dWplJpgSOj1bELOJBEDZBWMnwOC6PapE0+SRjnaLbp8IswqQTz78m3Evrcrze2p90TQzvui23D2yo9mxncQc8+dXh1o9J+3u3ODA+6y32CR/gX5hkiO3fKBXjOh0bLBy0nGW1xU7zNTlc//7lv+rbDQHXTp4W+lImZdA7TyGbBHNOA95zGW1BrxIZO2d7A72AxqUBYfkYKN/Ml6TsTMeW+IHpbeT4T39JFngq2fDzBPd+zcUWZLJLTDcUoiDlAZ0DSiTet4OIqRgJS2Mm3iktsbLov76CHgd4zDL3gJG4KeIbWrvNw2nrPANk6EY1PEpBgU+oe1u1zlesYlj10koaTg+AooikHWZc/JgAIAdjY4tfEonAUJ/dirbzCmCkXWuCnX/7ZVVsE7RpSLCQ9HE/uVVC2r71O7dTGaFsm14q3tsmceqkw/ha5ZyLsZhan9GitLST2bNerZn3QFMJI3sviLdECm1GSbGY3shVSIeeKy1GhTUINXXQfyldmHhgfrgJpo7T1U0Q9iUdtE9mX4MaLhJkHlnPsKqH+StKnB3AHmxDXXWqCPcHw=
        bucket: $S3_BUCKET
        local_dir: artifacts
        upload_dir: $S3_ARTIFACTS_PATH
        acl: public_read
        region: eu-west-2
        skip_cleanup: true
        on:
          all_branches: true
      after_deploy: rm -rf artifacts
      env:
        - SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - SCL_BUILD_MOCK=false
        - SCL_BUILD_OS=$TRAVIS_OS_NAME
      os: osx
    - stage: build
      name: "build mock"
      script: set -x; scripts/build-mock
      after_script: make strip-artifacts
      before_cache:
        - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
        - bash cargo_install.sh cargo-prune;
        - cargo prune
      before_deploy: make package-build-artifacts
      deploy:
        provider: s3
        access_key_id: AKIAIYOCYHBTBC6XUFYQ
        secret_access_key:
          secure: NQnKN7Tk4EG3psaOJLdrZexHtaEeFdECH5u5buvILKkZgyphLafu6P5zqX5XyIZqoL30WjR1aF71HQhZvQwgoCxT6cr/8rk9dXFu6ZLXJ8dCqEN5I/cc9dWplJpgSOj1bELOJBEDZBWMnwOC6PapE0+SRjnaLbp8IswqQTz78m3Evrcrze2p90TQzvui23D2yo9mxncQc8+dXh1o9J+3u3ODA+6y32CR/gX5hkiO3fKBXjOh0bLBy0nGW1xU7zNTlc//7lv+rbDQHXTp4W+lImZdA7TyGbBHNOA95zGW1BrxIZO2d7A72AxqUBYfkYKN/Ml6TsTMeW+IHpbeT4T39JFngq2fDzBPd+zcUWZLJLTDcUoiDlAZ0DSiTet4OIqRgJS2Mm3iktsbLov76CHgd4zDL3gJG4KeIbWrvNw2nrPANk6EY1PEpBgU+oe1u1zlesYlj10koaTg+AooikHWZc/JgAIAdjY4tfEonAUJ/dirbzCmCkXWuCnX/7ZVVsE7RpSLCQ9HE/uVVC2r71O7dTGaFsm14q3tsmceqkw/ha5ZyLsZhan9GitLST2bNerZn3QFMJI3sviLdECm1GSbGY3shVSIeeKy1GhTUINXXQfyldmHhgfrgJpo7T1U0Q9iUdtE9mX4MaLhJkHlnPsKqH+StKnB3AHmxDXXWqCPcHw=
        bucket: $S3_BUCKET
        local_dir: artifacts
        upload_dir: $S3_ARTIFACTS_PATH
        acl: public_read
        region: eu-west-2
        skip_cleanup: true
        on:
          all_branches: true
      after_deploy: rm -rf artifacts
      env:
        - SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - SCL_BUILD_MOCK=true
        - SCL_BUILD_OS=$TRAVIS_OS_NAME
      os: osx

    - stage: tests
      name: "mock tests"
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
        - make retrieve-build-artifacts
      script: make test-artifacts-mock
      env:
        - SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - SCL_BUILD_MOCK=true
        - SCL_BUILD_OS=$TRAVIS_OS_NAME
      os: linux
    - stage: tests
      name: "integration tests"
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
        - make retrieve-build-artifacts
      script: make test-artifacts-integration
      env:
        - SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - SCL_BUILD_MOCK=true
        - SCL_BUILD_OS=$TRAVIS_OS_NAME
      os: linux
    - stage: tests
      name: "binary compatibility tests"
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
        - make retrieve-build-artifacts
        - aws s3 cp --no-sign-request --region eu-west-2 s3://$S3_BUCKET/$S3_ARTIFACTS_PATH/binary-compatibility-tests ~/binary-compatibility-tests
      script: make test-artifacts-binary
      before_deploy:
        - find artifacts ! -name 'safe_authenticator-*' -exec rm '{}' \;
        - rm artifacts/*.d
        - mv artifacts/safe_authenticator-* artifacts/binary-compatibility-tests
      deploy:
        provider: s3
        access_key_id: AKIAIYOCYHBTBC6XUFYQ
        secret_access_key:
          secure: NQnKN7Tk4EG3psaOJLdrZexHtaEeFdECH5u5buvILKkZgyphLafu6P5zqX5XyIZqoL30WjR1aF71HQhZvQwgoCxT6cr/8rk9dXFu6ZLXJ8dCqEN5I/cc9dWplJpgSOj1bELOJBEDZBWMnwOC6PapE0+SRjnaLbp8IswqQTz78m3Evrcrze2p90TQzvui23D2yo9mxncQc8+dXh1o9J+3u3ODA+6y32CR/gX5hkiO3fKBXjOh0bLBy0nGW1xU7zNTlc//7lv+rbDQHXTp4W+lImZdA7TyGbBHNOA95zGW1BrxIZO2d7A72AxqUBYfkYKN/Ml6TsTMeW+IHpbeT4T39JFngq2fDzBPd+zcUWZLJLTDcUoiDlAZ0DSiTet4OIqRgJS2Mm3iktsbLov76CHgd4zDL3gJG4KeIbWrvNw2nrPANk6EY1PEpBgU+oe1u1zlesYlj10koaTg+AooikHWZc/JgAIAdjY4tfEonAUJ/dirbzCmCkXWuCnX/7ZVVsE7RpSLCQ9HE/uVVC2r71O7dTGaFsm14q3tsmceqkw/ha5ZyLsZhan9GitLST2bNerZn3QFMJI3sviLdECm1GSbGY3shVSIeeKy1GhTUINXXQfyldmHhgfrgJpo7T1U0Q9iUdtE9mX4MaLhJkHlnPsKqH+StKnB3AHmxDXXWqCPcHw=
        bucket: $S3_BUCKET
        local_dir: artifacts
        upload_dir: $S3_ARTIFACTS_PATH
        acl: public_read
        region: eu-west-2
        skip_cleanup: true
        on:
          all_branches: true
      env:
        - SCL_BCT_PATH=/home/travis/binary-compatibility-tests
        - SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - SCL_BUILD_MOCK=true
        - SCL_BUILD_OS=$TRAVIS_OS_NAME
      os: linux
    - stage: tests
      name: "mock/integration tests"
      script: set -x; scripts/test-mock && scripts/test-integration
      os: osx
    # Temporarily disable clippy
    # - stage: tests
    #   script: set -x; scripts/clippy-all
    #   if: type = pull_request
    #   os: linux

    - stage: deploy
      name: "package artifacts and deploy"
      install: pip install --user awscli
      before_script:
        - docker pull maidsafe/safe-client-libs-build:0.9.0
        - make retrieve-all-build-artifacts
      script: make package-deploy-artifacts
      deploy:
        provider: s3
        access_key_id: AKIAIA2TXTG7EV5VIG2Q
        secret_access_key:
          secure: qEDay6TCAy3tBLqLYFOx9OjAdoRl010paK2//teFETfwUfJA/RtNSfkp1yrgx+kZ3FO8cthdDnwR3zjM3pkCL+5mGkQMAgvRY7rcEB5H1VyO4jkZRoB4n/yUu5jB4dHdeeRWTOJxNOOPA0G1Q65LLkJql2JGoJatqE3pBmJm0X8=
        bucket: safe-client-libs
        local-dir: deploy
        acl: public_read
        region: eu-west-2
        skip_cleanup: true
        on:
          branch: refactor_artifacts_to_s3
          tags: false
      after_deploy:
        - rm -rf deploy
        - rm -rf artifacts
      if: type = push
      env: SCL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
      os: linux
sudo: false
cache:
  # Double the default timeout.
  timeout: 360
  cargo: true
  directories:
    - "${HOME}/.cache/master"
before_script:
  - scripts/version-check
after_script:
  - if [[ $TRAVIS_EVENT_TYPE = pull_request && -n $(git diff --shortstat 2> /dev/null | tail -n1) ]]; then
      echo "Working tree is dirty after building.  Probably Cargo.lock should be updated.";
      git status;
      travis_terminate 1;
    fi
