environment:
  global:
    RUST_BACKTRACE: 1
    SAFE_MEMORY_STORE: 1
  matrix:
    - RUST_TOOLCHAIN: 1.19.0

cache:
  - '%USERPROFILE%\.cargo'
  - '%APPVEYOR_BUILD_FOLDER%\target'

clone_depth: 1

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/appveyor/install_rustup.ps1"
        Invoke-WebRequest $url -OutFile "install_rustup.ps1"
        . ".\install_rustup.ps1"

platform:
  - x86
  - x64

configuration:
  - Release

skip_tags: true

build_script:
  - |-
    cargo check --verbose --release --lib --tests --manifest-path=ffi_utils/Cargo.toml
    cargo check --verbose --release --features testing --lib --tests --manifest-path=safe_core/Cargo.toml
    cargo check --verbose --release --features testing --lib --tests --manifest-path=safe_app/Cargo.toml
    cargo check --verbose --features testing --release --lib --tests --manifest-path=safe_authenticator/Cargo.toml

test_script:
  - |-
    cargo test --verbose --release --manifest-path=ffi_utils/Cargo.toml
    cargo test --verbose --release --features=use-mock-routing,testing --manifest-path=safe_core/Cargo.toml
    cargo test --verbose --release --features=use-mock-routing,testing --manifest-path=safe_app/Cargo.toml
    cargo test --verbose --release --features=use-mock-routing,testing --manifest-path=safe_authenticator/Cargo.toml

before_deploy:
  - cargo build --verbose --release --features=use-mock-routing,testing --manifest-path=safe_app/Cargo.toml
  - cargo build --verbose --release --features=use-mock-routing,testing --manifest-path=safe_authenticator/Cargo.toml
  - strip target\release\safe_app.dll target\release\safe_authenticator.dll
  - ps: |
        $env:SAFE_APP_VERSION = (cargo pkgid --manifest-path=safe_app/Cargo.toml) -Replace '.*[:#](.*)', 'v$1'
        $env:SAFE_AUTHENTICATOR_VERSION = (cargo pkgid --manifest-path=safe_authenticator/Cargo.toml) -Replace '.*[:#](.*)', 'v$1'
        Push-AppveyorArtifact target\release\safe_app.dll -FileName safe_app-mock-$env:SAFE_APP_VERSION-win-$env:PLATFORM.zip
        Push-AppveyorArtifact target\release\safe_authenticator.dll -FileName safe_authenticator-mock-$env:SAFE_AUTHENTICATOR_VERSION-win-$env:PLATFORM.zip
  - cargo build --verbose --release --manifest-path=safe_app/Cargo.toml
  - cargo build --verbose --release --manifest-path=safe_authenticator/Cargo.toml
  - strip target\release\safe_app.dll target\release\safe_authenticator.dll
  - ps: |
        Push-AppveyorArtifact target\release\safe_app.dll -FileName safe_app-$env:SAFE_APP_VERSION-win-$env:PLATFORM.zip
        Push-AppveyorArtifact target\release\safe_authenticator.dll -FileName safe_authenticator-$env:SAFE_AUTHENTICATOR_VERSION-win-$env:PLATFORM.zip

deploy:
  provider: S3
  access_key_id: AKIAIA2TXTG7EV5VIG2Q
  secret_access_key:
    secure: bj+Mv0HEJazcY+q3Lt16Ui/PjJwTO8GNRAmsZeOO4GYG2LJyhCqpNja1zrs0LHcv
  bucket: safe-client-libs
  region: eu-west-2
  set_public: true
  folder: $(APPVEYOR_REPO_COMMIT)
  artifact: /.*\.zip/
  on:
    branch: master
    RUST_TOOLCHAIN: 1.19.0
