environment:
  global:
    RUST_BACKTRACE: 1
  matrix:
    - RUST_VERSION: stable

branches:
  only:
    - master
    - dev

clone_depth: 1

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/AppVeyor"
        cmd /c curl -fsSL -o "Install Rustup.ps1" "$url/Install%20Rustup.ps1"
        . ".\Install Rustup.ps1"

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  - cmd: >-
      cd ffi_utils          ; cargo rustc --verbose --release -- --test -Zno-trans
      cd safe_core          ; cargo rustc --verbose --release -- --test -Zno-trans
      cd safe_app           ; cargo rustc --verbose --release -- --test -Zno-trans
      cd safe_authenticator ; cargo rustc --verbose --release -- --test -Zno-trans

test_script:
  - cmd: >-
      cd ffi_utils          ; cargo test --verbose --release
      cd safe_core          ; cargo test --verbose --release --features use-mock-routing
      cd safe_app           ; cargo test --verbose --release --features use-mock-routing
      cd safe_authenticator ; cargo test --verbose --release --features use-mock-routing
