environment:
  global:
    RUST_BACKTRACE: 1
    RUSTFLAGS: "-D warnings"
  matrix:
    - RUST_TOOLCHAIN: stable

cache:
  - '%USERPROFILE%\.cargo'
  - '%APPVEYOR_BUILD_FOLDER%\target'

clone_depth: 1

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/appveyor/install_rustup.ps1"
        Invoke-WebRequest $url -OutFile "install_rustup.ps1"
        . ".\install_rustup.ps1"

platform:
  - x64

configuration:
  - Release

skip_tags: true

before_build:
  - ps: |
        $COMMIT_MESSAGE = "$env:APPVEYOR_REPO_COMMIT_MESSAGE $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"
        if ($COMMIT_MESSAGE -match "[Vv]ersion change.*safe_authenticator to ([^;]+)") {
          $COMMIT_MESSAGE_VERSION = "v" + $Matches[1]
          $env:SAFE_AUTHENTICATOR_VERSION = (cargo pkgid --manifest-path=safe_authenticator/Cargo.toml) -Replace '.*[:#](.*)', 'v$1'
          if ($COMMIT_MESSAGE_VERSION -ne $env:SAFE_AUTHENTICATOR_VERSION) {
            Write-Error "Version mismatch between commit message and Cargo.toml for safe_authenticator."
            exit 1
          }
        } else {
          $env:SAFE_AUTHENTICATOR_VERSION = $env:APPVEYOR_REPO_COMMIT.Substring(0,7)
        }
        if ($COMMIT_MESSAGE -match "[Vv]ersion change.*safe_app to ([^;]+)") {
          $COMMIT_MESSAGE_VERSION = "v" + $Matches[1]
          $env:SAFE_APP_VERSION = (cargo pkgid --manifest-path=safe_app/Cargo.toml) -Replace '.*[:#](.*)', 'v$1'
          if ($COMMIT_MESSAGE_VERSION -ne $env:SAFE_APP_VERSION) {
            Write-Error "Version mismatch between commit message and Cargo.toml for safe_app."
            exit 1
          }
        } else {
          $env:SAFE_APP_VERSION = $env:APPVEYOR_REPO_COMMIT.Substring(0,7)
        }

build_script:
  - |-
    cargo check --verbose --release --features mock-network --lib --tests --manifest-path=safe_core/Cargo.toml
    cargo check --verbose --release --features mock-network --lib --tests --manifest-path=safe_authenticator/Cargo.toml
    cargo check --verbose --release --features mock-network --lib --tests --manifest-path=safe_app/Cargo.toml
    cargo check --verbose --release --features mock-network --lib --tests --manifest-path=tests/Cargo.toml

after_build:
  - ps: |
        if (git diff --shortstat) {
          Write-Error "Working tree is dirty after building.  Probably Cargo.lock should be updated."
          git status
          exit 1
        }

test_script:
  - |-
    cargo test --verbose --release --features=mock-network --manifest-path=safe_core/Cargo.toml
    cargo test --verbose --release --features=mock-network --manifest-path=safe_authenticator/Cargo.toml
    cargo test --verbose --release --features=mock-network --manifest-path=safe_app/Cargo.toml
