[package]
name          = "safe_client"
version       = "0.1.2"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
description   = "SAFE Client API library"
documentation = "http://maidsafe.github.io/safe_client/latest/"
repository    = "https://github.com/maidsafe/safe_client"
readme        = "README.md"
license       = "GPL-3.0"
homepage      = "http://maidsafe.net"

[dependencies]
# ---- MaidSafe -----
routing         = "0.2.*"
lru_time_cache  = "0.2.*"
self_encryption = "*"

# ---- Others ----
cbor            = "*"
rand            = "*"
sodiumoxide     = "*"
rust-crypto     = "*"
rustc-serialize = "*"

[features]
USE_ACTUAL_ROUTING = []
