[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://docs.maidsafe.net/safe_core/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.19.0"

[dependencies]
bincode = "~0.5.9"
clippy = {version = "~0.0.79", optional = true}
config_file_handler = "~0.4.0"
libc = "~0.2.14"
log = "~0.3.6"
lru-cache = "~0.0.7"
maidsafe_utilities = "~0.9.0"
rand = "~0.3.14"

# routing = "~0.23.4"
routing = { git = "https://github.com/afck/routing.git", branch = "0.23" }

rust_sodium = "~0.1.1"
rustc-serialize = "~0.3.19"
self_encryption = "~0.7.0"
time = "~0.1.35"
unwrap = "~1.1.0"

[dev-dependencies]
docopt = "~0.6.81"
regex = "~0.1.73"

[[example]]
bench = false
name = "client_stress_test"

[[example]]
bench = false
name = "self_authentication"

[[example]]
bench = false
name = "safe_client"

[[example]]
bench = false
name = "nfs_api"

[[example]]
bench = false
name = "simulate_browser"

[features]
use-mock-routing = []

[lib]
crate_type = ["staticlib", "rlib", "cdylib"]
name = "safe_core"
