[package]
authors = [ "MaidSafe Developers <dev@maidsafe.net>" ]
description = "Safe Network Client"
documentation = "https://docs.rs/sn_client"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_client"
readme = "README.md"
repository = "https://github.com/maidsafe/sn_client"
version = "0.46.2"
keywords = [ "Safe", "Network", "SafeNetwork" ]

[package.metadata.docs.rs]
features = [ "simulated-payouts" ]

[dependencies]
anyhow = "1.0.36"
async-trait = "~0.1.41"
bincode = "1.2.1"
crdts = "~4.3.0"
dirs-next = "1.0.1"
env_logger = "~0.6.2"
futures = "~0.3.5"
futures-util = "~0.3.4"
lazy_static = "1.4.0"
log = "~0.4.8"
qp2p = "~0.9.13"
rand = "~0.7.3"
regex = "1.3.1"
rmp-serde = "~0.15.1"
sha3 = "~0.8.2"
self_encryption = "~0.19.4"
serde_json = "1.0.53"
serde-value = "~0.5.3"
sn_data_types = "~0.14.0"
sn_messaging = "3.0.0"
sn_transfers = "~0.3.0"
thiserror = "1.0.23"
threshold_crypto = "0.4.0"
tiny-keccak = "1.5.0"
unwrap = "1.2.0"
url = "2.1.0"
ws = "~0.9.1"
xor_name = "1.1.3"

  [dependencies.bytes]
  version = "1.0.1"
  features = [ "serde" ]

  [dependencies.chrono]
  version = "~0.4.0"
  features = [ "serde" ]

  [dependencies.log4rs]
  version = "~0.8.3"
  features = [ "toml_format" ]

  [dependencies.miscreant]
  version = "~0.4.2"
  features = [ "soft-aes" ]

  [dependencies.serde]
  version = "1.0.111"
  features = [ "derive", "rc" ]

  [dependencies.tokio]
  version = "~0.2.21"
  features = [ "rt-core", "blocking", "stream", "rt-util" ]

[dev-dependencies]
serde_json = "1.0.9"

[features]
default = [ "simulated-payouts" ]
simulated-payouts = [
  "sn_data_types/simulated-payouts",
  "sn_transfers/simulated-payouts",
  "sn_messaging/simulated-payouts"
]
testing = [ ]
