[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://maidsafe.github.io/safe_core/latest/"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.6.0"

[dependencies]
clippy = {version = "~0.0.44", optional = true}
log = "~0.3.5"
lru_time_cache = "~0.2.6"
maidsafe_utilities = "~0.2.0"
rand = "~0.3.14"
routing = "~0.7.0"
rustc-serialize = "~0.3.18"
self_encryption = "~0.2.5"
sodiumoxide = "~0.0.9"
xor_name = "~0.0.4"
mpid_messaging = "~0.1.0"

[features]
use-mock-routing = []
