[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://docs.maidsafe.net/safe_core/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0/MaidSafe.net Commercial License 1.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.15.0"

[dependencies]
bincode = "~0.5.6"
clippy = {version = "~0.0.74", optional = true}
libc = "~0.2.11"
log = "~0.3.6"
lru_time_cache = "~0.4.0"
maidsafe_utilities = "~0.6.0"
rand = "~0.3.14"
routing = "~0.21.0"
rustc-serialize = "~0.3.19"
safe_network_common = "~0.2.0"
self_encryption = "~0.5.0"
sodiumoxide = "~0.0.10"
time = "~0.1.35"

[dev-dependencies]
docopt = "~0.6.80"
regex = "~0.1.71"

[lib]
crate_type = ["staticlib", "dylib", "rlib"]
name = "safe_core"

[[example]]
bench = false
name = "client_stress_test"

[[example]]
bench = false
name = "self_authentication"

[[example]]
bench = false
name = "safe_client"

[[example]]
bench = false
name = "nfs_api"

[[example]]
bench = false
name = "simulate_browser"

[features]
use-mock-routing = []
