[package]

name = "maidsafe_client"
version = "0.0.1"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/maidsafe_client/"
repository = "https://github.com/dirvine/maidsafe_client"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
cbor = "*"
rustc-serialize = "*"
rust-crypto = "*"
lru_time_cache = "*"
maidsafe_types = "*"
routing = "*"
sodiumoxide = "0.0.4"
