[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE core"
documentation = "https://docs.rs/safe_core"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.26.1"
build = "build.rs"

[dependencies]
base64 = "~0.4.1"
chrono = { version = "~0.4.0", features = ["serde"] }
ffi_utils = { path = "../ffi_utils", version = "~0.2.0" }
fs2 = "~0.4.2"
futures = "~0.1.15"
lazy_static = "~0.2.4"
log = "~0.3.7"
lru-cache = "~0.1.0"
maidsafe_utilities = "~0.14.0"
rand = "~0.3.15"
routing = "~0.33.1"
rust_sodium = "~0.5.0"
serde = "~1.0.11"
serde_derive = "~1.0.11"
self_encryption = "~0.11.1"
tiny-keccak = "~1.3.1"
tokio-core = "~0.1.9"
unwrap = "~1.1.0"

[dev-dependencies]
docopt = "~0.7.0"
rustc-serialize = "~0.3.23"

[build-dependencies]
ffi_utils = { path = "../ffi_utils", version = "~0.2.0" }
unwrap = "~1.1.0"

[features]
use-mock-routing = []
testing = []

[[example]]
bench = false
name = "gen_invites"

[[example]]
bench = false
name = "client_stress_test"
