#!/bin/bash

commit_message=$1
if [[ -z "$commit_message" ]]; then
    echo "The latest commit message must be supplied to this script as an argument."
    echo "It will determine whether the packages to be deployed contain a version number or a commit hash."
    exit 1
fi

function package_linux() {
    if [[ "$commit_message" =~ [Vv]ersion[[:space:]]change.*safe_authenticator[[:space:]]to[[:space:]]([^;]+) ]]; then
        make package-artifacts-versioned
    else
        make package-artifacts-commit-hash
    fi
}

function package_osx() {
    if [[ "$commit_message" =~ [Vv]ersion[[:space:]]change.*safe_authenticator[[:space:]]to[[:space:]]([^;]+) ]]; then
        ./scripts/package.rs --lib --name safe_app -d target/deploy --mock
        ./scripts/package.rs --lib --name safe_app -d target/deploy
        ./scripts/package.rs --lib --name safe_authenticator -d target/deploy --mock
        ./scripts/package.rs --lib --name safe_authenticator -d target/deploy
    else
        ./scripts/package.rs --lib --name safe_app -d target/deploy --mock --commit
        ./scripts/package.rs --lib --name safe_app -d target/deploy --commit
        ./scripts/package.rs --lib --name safe_authenticator -d target/deploy --mock --commit
        ./scripts/package.rs --lib --name safe_authenticator -d target/deploy --commit
    fi
}

uname_output=$(uname -s)
case "${uname_output}" in
    Linux*)
        package_linux
        ;;
    Darwin*)
        package_osx
        ;;
esac

